SUBMODULE (BLUESTEIN_MOD) BLUESTEIN_DP_SMOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : REAL64, INT32
USE FFT992_MOD, ONLY : FFT992, FFT992_CC, SET99B

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = REAL64
INTEGER, PARAMETER :: JPIM = INT32

#define FFTB_PLAN      FFTB_PLAN_DP
#define FFTB_TYPE      FFTB_TYPE_DP
#define BLUESTEIN_INIT BLUESTEIN_IMPL_INIT_DP
#define BLUESTEIN_FFT  BLUESTEIN_IMPL_FFT_DP
#define BLUESTEIN_TERM BLUESTEIN_IMPL_TERM_DP
#define BLUESTEIN_PLAN_FFT BLUESTEIN_IMPL_PLAN_FFT_DP
#include "bluestein_impl.F90"

END SUBMODULE BLUESTEIN_DP_SMOD
