SUBMODULE (BLUESTEIN_MOD) BLUESTEIN_SP_SMOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : REAL32, INT32
USE FFT992_MOD, ONLY : FFT992, FFT992_CC, SET99B

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = REAL32
INTEGER, PARAMETER :: JPIM = INT32


#define FFTB_PLAN      FFTB_PLAN_SP
#define FFTB_TYPE      FFTB_TYPE_SP
#define BLUESTEIN_INIT BLUESTEIN_IMPL_INIT_SP
#define BLUESTEIN_FFT  BLUESTEIN_IMPL_FFT_SP
#define BLUESTEIN_PLAN_FFT BLUESTEIN_IMPL_PLAN_FFT_SP
#define BLUESTEIN_TERM BLUESTEIN_IMPL_TERM_SP
#include "bluestein_impl.F90"

END SUBMODULE BLUESTEIN_SP_SMOD
