MODULE BLUESTEIN_MOD

USE ISO_FORTRAN_ENV, ONLY : REAL32, REAL64, INT32
USE ISO_C_BINDING, ONLY : C_PTR
IMPLICIT NONE

PRIVATE
PUBLIC :: BLUESTEIN_INIT, BLUESTEIN_PLAN_FFT, BLUESTEIN_FFT, BLUESTEIN_RELEASE, FFTB_TYPE
PUBLIC :: LAYOUT_FIELD_CONTIGUOUS, LAYOUT_FFT_CONTIGUOUS

INTEGER(KIND=INT32), PARAMETER :: LAYOUT_FIELD_CONTIGUOUS = 1
INTEGER(KIND=INT32), PARAMETER :: LAYOUT_FFT_CONTIGUOUS = 2

TYPE FFT992_PLAN_SP
  REAL(KIND=REAL32),ALLOCATABLE   :: TRIGS(:)
  INTEGER(KIND=INT32),ALLOCATABLE :: NFAX(:)
END TYPE FFT992_PLAN_SP

TYPE FFT992_PLAN_DP
  REAL(KIND=REAL64),ALLOCATABLE   :: TRIGS(:)
  INTEGER(KIND=INT32),ALLOCATABLE :: NFAX(:)
END TYPE FFT992_PLAN_DP

TYPE FFTB_PLAN_SP
  INTEGER(KIND=INT32)             :: NSIZE = 0
  REAL(KIND=REAL32),ALLOCATABLE   :: HS(:,:,:)
  REAL(KIND=REAL32),ALLOCATABLE   :: H2XT(:,:,:)
  TYPE(FFT992_PLAN_SP), POINTER   :: FFT992_PLAN => NULL()
END TYPE FFTB_PLAN_SP

TYPE FFTB_TYPE_SP
  TYPE(FFT992_PLAN_SP), ALLOCATABLE :: FFT992_TABLE(:)
  TYPE(FFTB_PLAN_SP),ALLOCATABLE    :: FFTB(:)
END TYPE FFTB_TYPE_SP

TYPE FFTB_PLAN_DP
  INTEGER(KIND=INT32)             :: NSIZE = 0
  REAL(KIND=REAL64),ALLOCATABLE   :: HS(:,:,:)
  REAL(KIND=REAL64),ALLOCATABLE   :: H2XT(:,:,:)
  TYPE(FFT992_PLAN_DP), POINTER   :: FFT992_PLAN => NULL()
END TYPE FFTB_PLAN_DP

TYPE FFTB_TYPE_DP
  TYPE(FFT992_PLAN_DP), ALLOCATABLE :: FFT992_TABLE(:)
  TYPE(FFTB_PLAN_DP),ALLOCATABLE    :: FFTB(:)
END TYPE FFTB_TYPE_DP

TYPE FFTB_TYPE
  TYPE(FFTB_TYPE_SP) :: SP
  TYPE(FFTB_TYPE_DP) :: DP
END TYPE FFTB_TYPE

INTERFACE
  MODULE SUBROUTINE BLUESTEIN_IMPL_INIT_SP(TB, NFFTS)
    TYPE(FFTB_TYPE_SP), INTENT(INOUT) :: TB
    INTEGER(KIND=INT32), INTENT(IN) :: NFFTS(:)
  END SUBROUTINE BLUESTEIN_IMPL_INIT_SP

  MODULE SUBROUTINE BLUESTEIN_IMPL_INIT_DP(TB, NFFTS)
    TYPE(FFTB_TYPE_DP), INTENT(INOUT) :: TB
    INTEGER(KIND=INT32), INTENT(IN) :: NFFTS(:)
  END SUBROUTINE BLUESTEIN_IMPL_INIT_DP

  MODULE SUBROUTINE BLUESTEIN_IMPL_FFT_SP(TB, N, KSIGN, KLOT, PDAT, LAYOUT)
    TYPE(FFTB_TYPE_SP), INTENT(INOUT) :: TB
    INTEGER(KIND=INT32), INTENT(IN) :: N, KSIGN, KLOT
    REAL(KIND=REAL32), INTENT(INOUT) :: PDAT(:,:)
    INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: LAYOUT
  END SUBROUTINE BLUESTEIN_IMPL_FFT_SP

  MODULE SUBROUTINE BLUESTEIN_IMPL_FFT_DP(TB, N, KSIGN, KLOT, PDAT, LAYOUT)
    TYPE(FFTB_TYPE_DP), INTENT(INOUT) :: TB
    INTEGER(KIND=INT32), INTENT(IN) :: N, KSIGN, KLOT
    REAL(KIND=REAL64), INTENT(INOUT) :: PDAT(:,:)
    INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: LAYOUT
  END SUBROUTINE BLUESTEIN_IMPL_FFT_DP

  MODULE SUBROUTINE BLUESTEIN_IMPL_TERM_SP(TB)
    TYPE(FFTB_TYPE_SP), INTENT(INOUT) :: TB
  END SUBROUTINE BLUESTEIN_IMPL_TERM_SP

  MODULE SUBROUTINE BLUESTEIN_IMPL_TERM_DP(TB)
    TYPE(FFTB_TYPE_DP), INTENT(INOUT) :: TB
  END SUBROUTINE BLUESTEIN_IMPL_TERM_DP

  MODULE SUBROUTINE BLUESTEIN_IMPL_PLAN_FFT_SP(TB, N)
    TYPE(FFTB_TYPE_SP), INTENT(INOUT), TARGET :: TB
    INTEGER(KIND=INT32), INTENT(IN) :: N
  END SUBROUTINE BLUESTEIN_IMPL_PLAN_FFT_SP

  MODULE SUBROUTINE BLUESTEIN_IMPL_PLAN_FFT_DP(TB, N)
    TYPE(FFTB_TYPE_DP), INTENT(INOUT), TARGET :: TB
    INTEGER(KIND=INT32), INTENT(IN) :: N
  END SUBROUTINE BLUESTEIN_IMPL_PLAN_FFT_DP
END INTERFACE

INTERFACE BLUESTEIN_FFT
  MODULE PROCEDURE BLUESTEIN_FFT_SP
  MODULE PROCEDURE BLUESTEIN_FFT_DP
  MODULE PROCEDURE BLUESTEIN_FFT_SP_1D
  MODULE PROCEDURE BLUESTEIN_FFT_DP_1D
END INTERFACE BLUESTEIN_FFT

CONTAINS

SUBROUTINE BLUESTEIN_INIT(TB, KIND, NFFTS)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  INTEGER(KIND=INT32), INTENT(IN) :: KIND
  INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: NFFTS(:)
  INTEGER(KIND=INT32), ALLOCATABLE :: EFFECTIVE_NFFTS(:)
  IF (PRESENT(NFFTS)) THEN
    IF (ANY(NFFTS < 1_INT32)) THEN
      CALL ABOR1('BLUESTEIN_INIT: NFFTS VALUES MUST BE >= 1')
    END IF
    EFFECTIVE_NFFTS = NFFTS
  ELSE
    ! No pre-planning requested. Plans are created lazily in BLUESTEIN_PLAN_FFT.
    RETURN
  END IF
  IF (KIND == REAL32) THEN
    CALL BLUESTEIN_IMPL_INIT_SP(TB%SP, EFFECTIVE_NFFTS)
  ELSE IF (KIND == REAL64) THEN
    CALL BLUESTEIN_IMPL_INIT_DP(TB%DP, EFFECTIVE_NFFTS)
  ELSE
    CALL ABOR1('BLUESTEIN_INIT: INVALID KIND')
  END IF
END SUBROUTINE BLUESTEIN_INIT

SUBROUTINE BLUESTEIN_FFT_SP(TB, N, KSIGN, KLOT, PDAT, INC, JUMP)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  INTEGER(KIND=INT32), INTENT(IN) :: N, KSIGN, KLOT
  REAL(KIND=REAL32), INTENT(INOUT) :: PDAT(:,:)
  INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: INC, JUMP
  INTEGER(KIND=INT32) :: EFFECTIVE_LAYOUT
  CALL BLUESTEIN_RESOLVE_LAYOUT(N, KLOT, INC, JUMP, EFFECTIVE_LAYOUT)
  CALL BLUESTEIN_IMPL_FFT_SP(TB%SP, N, KSIGN, KLOT, PDAT, EFFECTIVE_LAYOUT)
END SUBROUTINE BLUESTEIN_FFT_SP

SUBROUTINE BLUESTEIN_FFT_DP(TB, N, KSIGN, KLOT, PDAT, INC, JUMP)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  INTEGER(KIND=INT32), INTENT(IN) :: N, KSIGN, KLOT
  REAL(KIND=REAL64), INTENT(INOUT) :: PDAT(:,:)
  INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: INC, JUMP
  INTEGER(KIND=INT32) :: EFFECTIVE_LAYOUT
  CALL BLUESTEIN_RESOLVE_LAYOUT(N, KLOT, INC, JUMP, EFFECTIVE_LAYOUT)
  CALL BLUESTEIN_IMPL_FFT_DP(TB%DP, N, KSIGN, KLOT, PDAT, EFFECTIVE_LAYOUT)
END SUBROUTINE BLUESTEIN_FFT_DP

SUBROUTINE BLUESTEIN_FFT_SP_1D(TB, N, KSIGN, KLOT, PDAT, INC, JUMP)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  INTEGER(KIND=INT32), INTENT(IN) :: N, KSIGN, KLOT
  REAL(KIND=REAL32), INTENT(INOUT), TARGET, CONTIGUOUS :: PDAT(:)
  INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: INC, JUMP
  REAL(KIND=REAL32), POINTER :: PDAT_2D(:,:)
  INTEGER(KIND=INT32) :: ICLEN, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP, REQUIRED_SIZE

  ICLEN = 2 * (N / 2 + 1)
  CALL BLUESTEIN_RESOLVE_LAYOUT(N, KLOT, INC, JUMP, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP)
  REQUIRED_SIZE = BLUESTEIN_REQUIRED_SIZE(ICLEN, KLOT, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP)

  IF (SIZE(PDAT) < REQUIRED_SIZE) THEN
    CALL ABOR1('BLUESTEIN_FFT: BUFFER TOO SMALL')
  END IF

  SELECT CASE (EFFECTIVE_LAYOUT)
  CASE (LAYOUT_FIELD_CONTIGUOUS)
    PDAT_2D(1:KLOT,1:ICLEN) => PDAT(1:REQUIRED_SIZE)
  CASE (LAYOUT_FFT_CONTIGUOUS)
    PDAT_2D(1:EFFECTIVE_JUMP,1:KLOT) => PDAT(1:REQUIRED_SIZE)
  CASE DEFAULT
    CALL ABOR1('BLUESTEIN_FFT: INVALID LAYOUT')
  END SELECT

  CALL BLUESTEIN_IMPL_FFT_SP(TB%SP, N, KSIGN, KLOT, PDAT_2D, EFFECTIVE_LAYOUT)
END SUBROUTINE BLUESTEIN_FFT_SP_1D

SUBROUTINE BLUESTEIN_FFT_DP_1D(TB, N, KSIGN, KLOT, PDAT, INC, JUMP)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  INTEGER(KIND=INT32), INTENT(IN) :: N, KSIGN, KLOT
  REAL(KIND=REAL64), INTENT(INOUT), TARGET, CONTIGUOUS :: PDAT(:)
  INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: INC, JUMP
  REAL(KIND=REAL64), POINTER :: PDAT_2D(:,:)
  INTEGER(KIND=INT32) :: ICLEN, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP, REQUIRED_SIZE

  ICLEN = 2 * (N / 2 + 1)
  CALL BLUESTEIN_RESOLVE_LAYOUT(N, KLOT, INC, JUMP, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP)
  REQUIRED_SIZE = BLUESTEIN_REQUIRED_SIZE(ICLEN, KLOT, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP)

  IF (SIZE(PDAT) < REQUIRED_SIZE) THEN
    CALL ABOR1('BLUESTEIN_FFT: BUFFER TOO SMALL')
  END IF

  SELECT CASE (EFFECTIVE_LAYOUT)
  CASE (LAYOUT_FIELD_CONTIGUOUS)
    PDAT_2D(1:KLOT,1:ICLEN) => PDAT(1:REQUIRED_SIZE)
  CASE (LAYOUT_FFT_CONTIGUOUS)
    PDAT_2D(1:EFFECTIVE_JUMP,1:KLOT) => PDAT(1:REQUIRED_SIZE)
  CASE DEFAULT
    CALL ABOR1('BLUESTEIN_FFT: INVALID LAYOUT')
  END SELECT

  CALL BLUESTEIN_IMPL_FFT_DP(TB%DP, N, KSIGN, KLOT, PDAT_2D, EFFECTIVE_LAYOUT)
END SUBROUTINE BLUESTEIN_FFT_DP_1D

SUBROUTINE BLUESTEIN_RESOLVE_LAYOUT(N, KLOT, INC, JUMP, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP)
  IMPLICIT NONE
  INTEGER(KIND=INT32), INTENT(IN) :: N, KLOT
  INTEGER(KIND=INT32), INTENT(IN), OPTIONAL :: INC, JUMP
  INTEGER(KIND=INT32), INTENT(OUT) :: EFFECTIVE_LAYOUT
  INTEGER(KIND=INT32), INTENT(OUT), OPTIONAL :: EFFECTIVE_JUMP
  INTEGER(KIND=INT32) :: ICLEN

  ICLEN = 2 * (N / 2 + 1)
  EFFECTIVE_LAYOUT = LAYOUT_FIELD_CONTIGUOUS
  IF (PRESENT(EFFECTIVE_JUMP)) EFFECTIVE_JUMP = ICLEN

  IF (PRESENT(INC) .NEQV. PRESENT(JUMP)) THEN
    CALL ABOR1('BLUESTEIN_FFT: INC AND JUMP MUST BOTH BE PRESENT OR BOTH BE ABSENT')
  ELSE IF (PRESENT(INC)) THEN
    IF (INC == KLOT .AND. JUMP == 1_INT32) THEN
      EFFECTIVE_LAYOUT = LAYOUT_FIELD_CONTIGUOUS
    ELSE IF (INC == 1_INT32 .AND. JUMP >= ICLEN) THEN
      EFFECTIVE_LAYOUT = LAYOUT_FFT_CONTIGUOUS
    ELSE
      write(0,*) 'INC=', INC, ' JUMP=', JUMP, ' ICLEN=', ICLEN, ' KLOT=', KLOT
      CALL ABOR1('BLUESTEIN_FFT: UNSUPPORTED INC/JUMP COMBINATION')
    END IF
    IF (PRESENT(EFFECTIVE_JUMP) .AND. EFFECTIVE_LAYOUT == LAYOUT_FFT_CONTIGUOUS) THEN
      EFFECTIVE_JUMP = JUMP
    END IF
  END IF
END SUBROUTINE BLUESTEIN_RESOLVE_LAYOUT

INTEGER(KIND=INT32) FUNCTION BLUESTEIN_REQUIRED_SIZE(ICLEN, KLOT, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP)
  IMPLICIT NONE
  INTEGER(KIND=INT32), INTENT(IN) :: ICLEN, KLOT, EFFECTIVE_LAYOUT, EFFECTIVE_JUMP

  SELECT CASE (EFFECTIVE_LAYOUT)
  CASE (LAYOUT_FIELD_CONTIGUOUS)
    BLUESTEIN_REQUIRED_SIZE = ICLEN * KLOT
  CASE (LAYOUT_FFT_CONTIGUOUS)
    BLUESTEIN_REQUIRED_SIZE = EFFECTIVE_JUMP * KLOT
  CASE DEFAULT
    CALL ABOR1('BLUESTEIN_FFT: INVALID LAYOUT')
  END SELECT
END FUNCTION BLUESTEIN_REQUIRED_SIZE

SUBROUTINE BLUESTEIN_PLAN_FFT(TB, KIND, N)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  INTEGER(KIND=INT32), INTENT(IN) :: KIND
  INTEGER(KIND=INT32), INTENT(IN) :: N
  IF (KIND == REAL32) THEN
    CALL BLUESTEIN_IMPL_PLAN_FFT_SP(TB%SP, N)
  ELSE IF (KIND == REAL64) THEN
    CALL BLUESTEIN_IMPL_PLAN_FFT_DP(TB%DP, N)
  ELSE
    CALL ABOR1('BLUESTEIN_PLAN_FFT: INVALID KIND')
  END IF
END SUBROUTINE BLUESTEIN_PLAN_FFT

SUBROUTINE BLUESTEIN_RELEASE(TB)
  IMPLICIT NONE
  TYPE(FFTB_TYPE), INTENT(INOUT) :: TB
  CALL BLUESTEIN_IMPL_TERM_SP(TB%SP)
  CALL BLUESTEIN_IMPL_TERM_DP(TB%DP)
END SUBROUTINE BLUESTEIN_RELEASE

END MODULE BLUESTEIN_MOD